// <auto-generated />
namespace CourseManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update201911121451 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update201911121451));
        
        string IMigrationMetadata.Id
        {
            get { return "201911120651193_Update201911121451"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
